I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 23, in script
    pause 3
  File "renpy/common/000statements.rpy", line 383, in execute_pause
    renpy.with_statement(Pause(delay))
IOError: Couldn't find file 'music/bg.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 23, in script
    pause 3
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\ast.py", line 1801, in execute
    self.call("execute")
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\ast.py", line 1789, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\statements.py", line 169, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 383, in execute_pause
    renpy.with_statement(Pause(delay))
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\exports.py", line 1409, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 2190, in do_with
    clear=clear)
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 2624, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\display\core.py", line 3284, in interact_core
    renpy.audio.audio.periodic()
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\audio\audio.py", line 976, in periodic_thread_main
    periodic_pass()
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\audio\audio.py", line 920, in periodic_pass
    c.periodic()
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\audio\audio.py", line 409, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\audio\audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "D:\Programm\RenPy\renpy-6.99.14.1-sdk\renpy\loader.py", line 555, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'music/bg.mp3'.

Windows-8-6.2.9200
Ren'Py 6.99.14.1.3218
Python-man 1.0
Tue Mar 13 15:59:21 2018
